In [1]:
#imports
import math
import random
import pandas as pd
import numpy as np
import os
import networkx as nx

In [2]:
excel_list1 = os.listdir("Raw_Data")
excel_list = []
for i in excel_list1:
    if(i.endswith(".csv")):
        excel_list.append(i)

In [21]:
for i in excel_list:
    path = "Raw_Data/"+i
    target = path[:9] + path[11:13] + path[9:11] + path[13:]
    print(path,target)
    #!mv $path $target

Raw_Data/1018.csv Raw_Data/1810.csv
Raw_Data/0815.csv Raw_Data/1508.csv
Raw_Data/0519.csv Raw_Data/1905.csv
Raw_Data/1119.csv Raw_Data/1911.csv
Raw_Data/0117.csv Raw_Data/1701.csv
Raw_Data/0816.csv Raw_Data/1608.csv
Raw_Data/0818.csv Raw_Data/1808.csv
Raw_Data/0616.csv Raw_Data/1606.csv
Raw_Data/1215.csv Raw_Data/1512.csv
Raw_Data/0119.csv Raw_Data/1901.csv
Raw_Data/1115.csv Raw_Data/1511.csv
Raw_Data/0617.csv Raw_Data/1706.csv
Raw_Data/0515.csv Raw_Data/1505.csv
Raw_Data/1219.csv Raw_Data/1912.csv
Raw_Data/0915.csv Raw_Data/1509.csv
Raw_Data/0917.csv Raw_Data/1709.csv
Raw_Data/0219.csv Raw_Data/1902.csv
Raw_Data/0817.csv Raw_Data/1708.csv
Raw_Data/0220.csv Raw_Data/2002.csv
Raw_Data/1019.csv Raw_Data/1910.csv
Raw_Data/0116.csv Raw_Data/1601.csv
Raw_Data/0319.csv Raw_Data/1903.csv
Raw_Data/0716.csv Raw_Data/1607.csv
Raw_Data/0919.csv Raw_Data/1909.csv
Raw_Data/0718.csv Raw_Data/1807.csv
Raw_Data/0620.csv Raw_Data/2006.csv
Raw_Data/0419.csv Raw_Data/1904.csv
Raw_Data/0417.csv Raw_Data/1

In [17]:
graphs = []
for i in excel_list:
    path = "Raw_Data/"+i
    excel = pd.read_csv(path ,header=0, index_col=0, usecols = [0,1,2,3,4] ,names=["SNo","city1","city2","to","from"] )
        
    #print(excel)
    G = nx.DiGraph()
    print(path)
    #print(len(excel))
    for i in range(1,len(excel)+1):
        weight1 = excel["to"][i]
        weight2 = excel["from"][i]
        G.add_edge(excel["city1"][i],excel["city2"][i],weight=weight1)
        G.add_edge(excel["city2"][i],excel["city1"][i],weight=weight2)
        #print(excel["city1"][i],excel["city2"][i])
    print(excel)
    print(nx.adjacency_matrix(G).todense())
    graphs.append(G)

Raw_Data/1018.csv
             city1          city2     to   from
SNo                                            
1          ADAMPUR          DELHI   2277   2251
2         AGARTALA        CHENNAI   4064   1791
3         AGARTALA           PUNE    405      0
4         AGARTALA  VISAKHAPATNAM    108      0
5    AGATTI ISLAND      BENGALURU   2299   2465
..             ...            ...    ...    ...
486       VADODARA         JAIPUR    781    578
487       VADODARA          KOCHI     20      0
488       VADODARA      MANGALORE    116      0
489       VADODARA         MUMBAI  23147  21970
490       VADODARA     PORT BLAIR     75      0

[490 rows x 4 columns]
[[   0 2277    0 ...    0    0    0]
 [2251    0 1921 ...    0    0    0]
 [   0 2039    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
Raw_Data/0815.csv
             city1      city2     to   from
SNo                                        


             city1          city2     to   from
SNo                                            
1          ADAMPUR          DELHI   2072   2097
2         AGARTALA        CHENNAI    878   1590
3         AGARTALA  VISAKHAPATNAM    110      0
4    AGATTI ISLAND          KOCHI   2542      0
5             AGRA          DELHI      0     14
..             ...            ...    ...    ...
508       VADODARA        JODHPUR     49      0
509       VADODARA          KOCHI     44      0
510       VADODARA      MANGALORE    103      0
511       VADODARA         MUMBAI  20536  19243
512     VIJAYAWADA  VISAKHAPATNAM      0   5369

[512 rows x 4 columns]
[[    0  2072     0 ...     0     0     0]
 [ 2097     0  1541 ...     0     0 20649]
 [    0  1453     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0 23157     0 ...     0     0     0]]
Raw_Data/0817.csv
             city1          city2     to   from
SNo                   

             city1          city2    to  from
SNo                                          
1             AGRA          DELHI     0    56
2             AGRA      KHAJURAHO   338     0
3             AGRA         JAIPUR   392   265
4             AGRA       VARANASI     0   965
5    AGATTI ISLAND          KOCHI  1294  1515
..             ...            ...   ...   ...
422     PUDUCHERRY     VIJAYAWADA     0    12
423         RAIPUR  VISAKHAPATNAM  1032     0
424       TIRUPATI     VIJAYAWADA   879   894
425     TRIVANDRUM        UDAIPUR    13     9
426     VIJAYAWADA  VISAKHAPATNAM  3773  3774

[426 rows x 4 columns]
[[  0   0 338 ...   0   0   0]
 [ 56   0 654 ...   0   0   0]
 [  0 892   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
Raw_Data/0820.csv
        city1          city2    to  from
SNo                                     
1    AGARTALA      BENGALURU   724  1502
2    AGARTALA        CHENNAI    32    35
3   

             city1          city2     to   from
SNo                                            
1         AGARTALA        CHENNAI    967    996
2         AGARTALA  VISAKHAPATNAM     69      0
3    AGATTI ISLAND          KOCHI   1020   1128
4             AGRA          DELHI      0     41
5             AGRA      KHAJURAHO    275      0
..             ...            ...    ...    ...
313       VADODARA      HYDERABAD    267    401
314       VADODARA        KOLKATA    717      0
315       VADODARA        LUCKNOW    151    289
316       VADODARA         MUMBAI  27946  25941
317     VIJAYAWADA  VISAKHAPATNAM   1730   1526

[317 rows x 4 columns]
[[    0   967    69 ...     0     0     0]
 [  996     0 13487 ...     0     0   505]
 [    0 12337     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0   420     0 ...     0     0     0]]
Raw_Data/0719.csv
          city1          city2    to  from
SNo                        

          city1          city2    to  from
SNo                                       
1      AGARTALA      BENGALURU  2372  1782
2      AGARTALA        CHENNAI   333   265
3      AGARTALA          DELHI  3738  3337
4      AGARTALA       GUWAHATI  1361   947
5      AGARTALA         IMPHAL   209   182
..          ...            ...   ...   ...
406      RAIPUR       SRINAGAR     0     3
407      RAIPUR  VISAKHAPATNAM     0     2
408      RAJKOT          SURAT    26     0
409    TIRUPATI  VISAKHAPATNAM   506   453
410  VIJAYAWADA  VISAKHAPATNAM    18    19

[410 rows x 4 columns]
[[    0  2372   333 ...     0     0     0]
 [ 1782     0 15638 ...     0     0     0]
 [  265 15866     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
Raw_Data/1217.csv
             city1          city2     to   from
SNo                                            
1         AGARTALA        CHENNAI   204